name: acnoo_flutter_admin_panel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  responsive_framework: ^1.4.0
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  country_flags: ^3.0.0
  iconly: ^1.0.1
  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296
  expansion_widget: ^0.1.0
  syncfusion_flutter_charts: ^26.1.41+1
  go_router: ^14.2.1
  fl_chart: ^0.68.0
  collection: ^1.18.0
  flutter_layout_grid: ^2.0.7
  syncfusion_flutter_calendar: ^26.2.4
  intl: ^0.19.0
  feather_icons: ^1.2.0
  flutter_animate: ^4.5.0
  table_calendar: ^3.1.2
  syncfusion_flutter_datagrid: ^26.2.9
  appflowy_board: ^0.1.2
  magicoon_icons: ^0.0.5
  flex_color_picker: ^3.5.1
  google_maps_flutter_web: ^0.5.10
  google_maps_flutter: ^2.9.0
  iconsax_plus: ^1.0.0
  syntax_highlight: ^0.4.0

  # Remote Packages
  responsive_grid:
    git: 
      url: https://github.com/iamtoricool/ResponsiveGrid_Flutter.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/widget_images/
    - assets/images/widget_images/banner_images/
    - assets/images/sidebar_icons/
    - assets/images/widget_images/dashboard_icon/
    - assets/images/widget_images/card_images/feature_card/
    - assets/images/widget_images/sm_icon/
    - assets/images/widget_images/authentication_images/
    - assets/images/widget_images/dashboard_overview_icon/
    - assets/images/widget_images/svg_icons/
    - assets/app_icons/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900
        