name: Build & Release

on:
  push:
    branches:
      - release

jobs:
  build-project:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.3'
      - run: flutter --version

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Flutter APKs
        run: flutter build apk --split-per-abi

      # - name: Build Flutter Web
      #   run: flutter build web --release --no-tree-shake-icons

      # - name: Archive Web Files
      #   uses: thedoctor0/zip-release@0.7.5
      #   with:
      #     path: ./build/web/
      #     filename: web.zip

      - name: Check Files
        run: ls -R ./build/

      - name: Create Upload Folder
        # run: mkdir uploadables && cd uploadables && cp ../web.zip ./ && cp ../build/app/outputs/flutter-apk/*.apk ./
        run: mkdir uploadables && cd uploadables && cp ../build/app/outputs/flutter-apk/*.apk ./
      
      - name: Upload to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create v${{ github.run_number }} .*

      # - name: Upload Build Files
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-files
      #     path: ./uploadables

  # release-build-files:
  #   name: Publish Build Files
  #   runs-on: ubuntu-latest
  #   needs: build-project
  #   steps:
  #   - name: Download Build Files
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: build-files
    
  #   - name: Test Download Files
  #     run: ls -R
    
    # - name: Create Github Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     name: release ${{ github.run_number }}
    #     tag_name: ${{ github.run_number }}
    #     files: |
    #       ./*.apk*
    #       ./web.zip

    # - name: Create Github Release
    #   id: create-github-release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.run_number }}
    #     release_name: Release ${{ github.run_number }}

    # - name: Upload Release Assets
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create-github-release.outputs.upload_url }}
    #     asset_path: ./*
    #     asset_name: acnoo_flutter_admin_panel_web_v${{ github.run_number }}.zip
    #     asset_content_type: application/zip
